### ISSUE TITLE
essentials release zip containing two different sized dlls?

### ISSUE THREAD

**Issue by cindylo** [dodexahedron/EssentialsPlugin#4]
Not sure if a compile or package error or not but recently the essentials zip has been having 2 DLLs in it. One in the folder and one outside

**Comment by dodexahedron** [comment]
That's definitely unintended.
I'll re-post the current one.

**Comment by dodexahedron** [comment]
Fixed:
https://github.com/dodexahedron/EssentialsPlugin/releases/tag/v1.2.1.2212-alpha
