### ISSUE TITLE
Inactive Scan not working

### ISSUE THREAD

**Issue by vizerei** [dodexahedron/EssentialsPlugin#6]
Using, for example, '/admin scan inactive 21' will return nothing to the console.  Using the command with no number (/admin scan inactive) will return an error about needing to be greater than 0.

**Comment by dodexahedron** [comment]
Good catch.
Would you mind re-posting this over at https://github.com/SEServerExtender/SEServerExtender/ , please?  I'll work on a fix in the meantime.
Closing this one.

**Comment by vizerei** [comment]
Sorry for disappearing for a while.  Work had me traveling and gearing up to go over seas.  The down side of going overseas is that for the immediate future I will be scarce.  The bright side is that once I get settled in (I'll be overseas for 6-12 months) I should be more time than ever to assist.

**Comment by dodexahedron** [comment]
Hey there.
We've moved development of all of the SESE-related stuff to https://github.com/SEServerExtender
Check out the new digs!
