### ISSUE TITLE
Please do not post new issues here

### ISSUE THREAD

**Issue by dodexahedron** [dodexahedron/EssentialsPlugin#9]
The project has moved to https://github.com/SEServerExtender/EssentialsPlugin
Please post all new issues there.
Issues posted here will be closed with a request to re-post on the new project page.

**Comment by devu** [comment]
So where to put them as under provided link README point back to this place again?

**Comment by dodexahedron** [comment]
Use the issues button on the right.
Thanks for pointing out the link in the readme, though.
I will update those.
